### ============================
### posts
### ============================

### posts.index
GET http://localhost:8080/day1009_t_common_response_war/posts
Accept: application/json

### posts.index by page
GET http://localhost:8080/day1009_t_common_response_war/posts?page=2&perPage=3
Accept: application/json

### posts.store
POST http://localhost:8080/day1009_t_common_response_war/posts
Content-Type: application/json

{
  "title": "post-title-11",
  "slug": "post-title-11",
  "cover": "/img/cover/default-cover.png",
  "description": "post-title-11 description",
  "content": "## post-title-11 content\nthe content paragraph 1...",
  "status": "1",
  "userId": "1"
}

### posts.show
GET http://localhost:8080/day1009_t_common_response_war/posts/11
Accept: application/json

### posts.update
PUT http://localhost:8080/day1009_t_common_response_war/posts/11
Content-Type: application/json

{
  "title": "post-title-11__update",
  "status": 0
}

### posts.delete
DELETE http://localhost:8080/day1009_t_common_response_war/posts/11
Content-Type: application/json



### ============================
### users
### ============================

### users.index
GET http://localhost:8080/day1009_t_common_response_war/users
Accept: application/json

### users.index by page
GET http://localhost:8080/day1009_t_common_response_war/users?page=2&perPage=1
Accept: application/json

### users.store
POST http://localhost:8080/day1009_t_common_response_war/users
Content-Type: application/json

{
  "name": "store-1",
  "email": "store-1@example.com",
  "password": "$2a$10$X/uMNuiis.fyO47cxbta3OSs2sllSeLcwVfC0.ghyxeVVZRmAbzk2",
  "status": -1
}

### users.show
GET http://localhost:8080/day1009_t_common_response_war/users/3
Accept: application/json

### users.update
PUT http://localhost:8080/day1009_t_common_response_war/users/3
Content-Type: application/json

{
  "name": "store-1__update",
  "status": 1
}

### users.delete
DELETE http://localhost:8080/day1009_t_common_response_war/users/3
Content-Type: application/json
