### user-param
GET http://localhost:8080/day0928_spring_mvc_war/user/param?name=alice&email=alice@example.com
Accept: application/json

### user-param-pojo
GET http://localhost:8080/day0928_spring_mvc_war/user/param-pojo?name=alice&email=alice@example.com
Accept: application/json

### user-body-pojo
GET http://localhost:8080/day0928_spring_mvc_war/user/body-pojo
Accept: application/json
Content-Type: application/json

{
  "name": "bob",
  "email": "bob@example.com"
}

### date-time-format
GET http://localhost:8080/day0928_spring_mvc_war/user/date-time-format?date=2023/10/1&dateYmd=2023-10-2&dateYmdHms=2023-10-2 08:09:10
Accept: application/json



### response/page
GET http://localhost:8080/day0928_spring_mvc_war/response/page
Accept: application/xhtml+xml

### response/text
GET http://localhost:8080/day0928_spring_mvc_war/response/text


### response/json
GET http://localhost:8080/day0928_spring_mvc_war/response/json
Accept: application/json
